MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.add_ResNet50_conv4_body
  NUM_CLASSES: 222
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  # 2x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 37500
  STEPS: [0, 25000, 33333]
RPN:
  SIZES: (6, 16, 32, 64, 128)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.add_ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('tt100k_trainval',)
  SCALES: (1600,)
  MAX_SIZE: 2048
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 128 #changed from 512 to 128, increase iter accordingly
TEST:
  DATASETS: ('tt100k_test',)
  SCALE: 1600
  MAX_SIZE: 2048
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: .
