MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.add_ResNet50_conv4_body
  NUM_CLASSES: 222
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0005 # originally 0.0001 for COCO
  LR_POLICY: steps_with_decay
  BASE_LR: 0.00125 #default is 0.01 for 8 GPUS
  GAMMA: 0.1

  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  # originally for 1x training: 180.000 MAX_ITER for 8 GPUS

  # COCO train: 118286 images, 860001 annotations (around 7.2 per image)
  # tt100k: 6105 images, 16527 annotations (around 2.7 per image)

  MAX_ITER: 160000 # COCO: default 180.000, doubled 80.000
  STEPS: [0, 108000, 142000] # doubled [0, 54000, 71000] , COCO: default [0, 120000, 160000]
RPN:
  SIZES: (8, 16, 32, 64, 128)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.add_ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('tt100k_trainval',)
  SCALES: (1600,)
  MAX_SIZE: 1600
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  SNAPSHOT_ITERS: 20000
  USE_FLIPPED: False
TEST:
  DATASETS: ('tt100k_test',)
  SCALE: 1600
  MAX_SIZE: 1600
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  FORCE_JSON_DATASET_EVAL: True
OUTPUT_DIR: .
