MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: VGG_CNN_M_1024.add_VGG_CNN_M_1024_conv5_body
  NUM_CLASSES: 46
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0005 # originally 0.0001 for COCO
  LR_POLICY: steps_with_decay
  BASE_LR: 0.00125 #default is 0.01 for 8 GPUS
  GAMMA: 0.1

  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  # originally for 1x training: 180.000 MAX_ITER for 8 GPUS

  # COCO train: 118286 images, 860001 annotations (around 7.2 per image)
  # tt100k: 6105 images, 16527 annotations (around 2.7 per image)

  MAX_ITER: 30 # doubled from 80000 # COCO: default 180.000
  STEPS: [0, 20, 25] # doubled from [0, 54000, 71000] # COCO: default [0, 120000, 160000]
  WARM_UP_ITERS: 10
RPN:
  SIZES: (8, 16, 32, 64, 128)
FAST_RCNN:
  ROI_BOX_HEAD: VGG_CNN_M_1024.add_VGG_CNN_M_1024_roi_fc_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  WEIGHTS: . # insert path
  DATASETS: ('tt100k_trainval_ignore_complete',)
  SCALES: (2048,)
  MAX_SIZE: 2048
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 128
  SNAPSHOT_ITERS: 3
  USE_FLIPPED: False
TEST:
  DATASETS: ('tt100k_test_ignore_complete',)
  SCALE: 2048
  MAX_SIZE: 2048
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
  FORCE_JSON_DATASET_EVAL: False
OUTPUT_DIR: .
CUSTOM_DATA:
  FORCE_TEST: True